project:
  type: website
  output-dir: docs

website:
  title: "BlakeActkinson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [cosmo, custom.scss]    
    toc: true